### ISSUE TITLE
Check compatibility with Windows 11

### ISSUE THREAD

**Issue by goanpeca** [albertosottile/darkdetect#13] opened 2021-09-16 18:06 UTC
Hi @albertosottile thanks for working on this :) 

I had a question:

Is this ifelse code https://github.com/albertosottile/darkdetect/blob/master/darkdetect/__init__.py#L19 working as expected?

Will it not work for other versions of windows besides 10 ?

thanks!

**Comment by albertosottile** [comment] 2021-09-19 14:57
I had to go to the mentioned PR to understand exactly what this issue was about, as I am not yet in the right mindset for Windows 11. Short answer: I have no idea if this package works under Windows 11, nor I have way to test it, nor I am sure on how to fix a potential failure. 

@goanpeca Would you like to open a PR with a fix? Maybe is it as easy as changing `==` with `>=`...

Side note: this is not as trivial as it might seem, as e.g. macOS 11.0 still has `platform.mac_ver() = '10.16'`. Hence, for whatever PR/solution, I would recommend some testing on the target system...

**Comment by GeoffIX** [comment] 2021-10-31 05:33
I have found a modification to the __init__.py which allows Windows 11 to be detected correctly.
I am running Windows 10 and Windows 11 in Parallels Desktop 17 virtual machines under macOS Big Sur.
I first confirmed that both Windows installs correctly responded to the windows registry commands to discover the current display theme. That led me to look at the version check being used.

Windows 11 still returns '10' from platform.release(), so that part is fine.

Instead of deriving winver from sys.getwindowsversion(), which was reporting 9200 on both win10 and win11 systems, I used the second component of platform.version() which gave me 19041 on win10 and 22000 on win11, after splitting the '10.X.XXXXX' platform.version() output 

    #winver = int(sys.getwindowsversion()[2])
    winver = int(platform.version().split('.')[2]) # This gives better build numbers in Parallels VM

**Comment by hussain5416** [comment] 2021-11-02 14:57
I will check it tomorrow

**Comment by hussain5416** [comment] 2021-11-03 02:11
@albertosottile I checked this issue with windows 11. Check the screenshot for the reason.
![image](https://user-images.githubusercontent.com/78584556/140001070-1b4522cb-904f-44a8-b97c-37d49949c61f.png)
### Yeah! Code still works for windows 11.

**Comment by hussain5416** [comment] 2021-11-03 02:30
As a precaution, I created a pull request regarding this #16

**Comment by albertosottile** [comment] 2021-11-10 22:03
Closed by #16

**Closed by albertosottile** 2021-11-10 22:03 UTC
Labels: help wanted
